apiVersion: v1
kind: Pod
metadata:
  name: postgresqldb
  labels:
    app: postgresqldb
spec:
  containers:
    - name: postgresql-db
      image: postgresql-db
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgresqldb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432